ch[1]="abdomen mostly orange"
ch[2]="end of abdomen orange"
ch[3]="end of abdomen white"
ch[4]="end of abdomen black"
ch[5]="5 white tergal bands"
ch[6]="4 white tergal bands"
ch[7]="3 white tergal bands"
ch[8]="2 white tergal bands"
ch[9]="lateral tergal hair only"
ch[10]="facial hair white"
ch[11]="facial hair orange"
ch[12]="clypeus with projection(s)"
ch[13]="length <10 mm"
ch[14]="length 10-12 mm"
ch[15]="length > 12 mm"
chcol[0]=0
chcol[1]=4
chcol[2]=9
chcol[3]=11
chcol[4]=12
chcol[5]=15
