mch[1]="fore tarsus modified"
mch[2]="fore tarsus unmodified"
mch[3]="most of abdomen orange"
mch[4]="end of abdomen red or gold"
mch[5]="end of abdomen white"
mch[6]="end of abdomen black"
mch[7]="abdomen without bands"
mch[8]="incomplete bands only"
mch[9]="end of antenna expanded"
mch[10]="T6 with sharp teeth"
mch[11]="facial hair white"
mch[12]="facial hair orange"
mch[13]="length <9 mm"
mch[14]="length 9-10 mm"
mch[15]="length 11-13 mm"
mchcol[0]=0
mchcol[1]=2
mchcol[2]=6
mchcol[3]=8
mchcol[4]=9
mchcol[5]=10
mchcol[6]=12
mchcol[7]=15
